#pragma once

#define ON_NETWORKING

#define SERVERIP	"127.0.0.1"
//#define SERVERIP	"192.168.103.222"
#define SERVERPORT	9000
#define WM_SOCKET WM_USER+1
#define MAX_BUFFER 1024
#define MAX_PACKET 256

typedef enum PKT_ID
{
	PKT_ID_PLAYER_INFO,
	PKT_ID_PLAYER_LIFE,
	PKT_ID_CREATE_OBJECT,
	PKT_ID_DELETE_OBJECT,
	PKT_ID_TIME_INFO,
	PKT_ID_SEND_COMPLETE,
	PKT_ID_UPDATE_OBJECT,
	PKT_ID_CREATE_EFFECT,
	PKT_ID_GAME_STATE,
	PKT_ID_PLAYER_IN,
	PKT_ID_PLAYER_OUT,
	PKT_ID_ROBBY_PLAYER_INFO,
	PKT_ID_LOAD_COMPLETE,
	PKT_ID_LOAD_COMPLETE_ALL,
	PKT_ID_PLAYER_ID,
	PKT_ID_GAME_START
}PKT_ID;

typedef enum OBJECT_TYPE
{
	OBJECT_TYPE_PLAYER,
	OBJECT_TYPE_MACHINE_BULLET,
	OBJECT_TYPE_OBSTACLE,
	OBJECT_TYPE_ITEM_HEALING,
	OBJECT_TYPE_BZK_BULLET,
	OBJECT_TYPE_BEAM_BULLET,
	OBJECT_TYPE_ITEM_AMMO
}OBJECT_TYPE;

typedef enum SCENE_NAME
{
	SCENE_NAME_COLONY
}SCENE_NAME;

enum GAME_STATE
{
	GAME_STATE_GAME_START,
	GAME_STATE_GAME_OVER,
	GAME_STATE_LOAD_COMPLETE
};
typedef enum EFFECT_TYPE
{
	EFFECT_TYPE_HIT_FONT,
	EFFECT_TYPE_EXPLOSION,
	EFFECT_TYPE_HIT
}EFFECT_TYPE;

enum EFFECT_ANIMATION_TYPE
{
	EFFECT_ANIMATION_TYPE_ONE,
	EFFECT_ANIMATION_TYPE_LOOP
};
enum WEAPON_TYPE
{
	WEAPON_TYPE_MACHINE_GUN,
	WEAPON_TYPE_BAZOOKA,
	WEAPON_TYPE_BEAM_RIFLE
};

enum ANIMATION_TYPE
{
	ANIMATION_TYPE_IDLE,
	ANIMATION_TYPE_WALK_FORWARD,
	ANIMATION_TYPE_WALK_RIGHT,
	ANIMATION_TYPE_WALK_LEFT,
	ANIMATION_TYPE_WALK_BAKCWARD,
	ANIMATION_TYPE_JUMP,
	ANIMATION_TYPE_LANDING,
	ANIMATION_TYPE_DASH_FORWARD,
	ANIMATION_TYPE_DASH_LEFT,
	ANIMATION_TYPE_DASH_RIGHT,
	ANIMATION_TYPE_DASH_BACKWARD,
	ANIMATION_TYPE_GM_GUN_STAND
};

enum BULLET_TYPE
{
	BULLET_TYPE_MACHINE_GUN,
	BULLET_TYPE_BAZOOKA,
	BULLET_TYPE_BEAM_RIFLE
};

typedef struct PKT_PLAYER_INFO
{
	char			PktId;
	char			PktSize;
	int				ID;
	XMFLOAT4X4		WorldMatrix;
	BOOL			IsShooting;
	XMFLOAT4X4		BulletWorldMatrix;
	WEAPON_TYPE		Player_Weapon;
	BOOL			isChangeWeapon;
	ANIMATION_TYPE	Player_Animation;
	BOOL			isChangeAnimation;
	int				State;
}PKT_PLAYER_INFO;

typedef struct PKT_PLAYER_LIFE
{
	char		PktId;
	char		PktSize;
	int			ID;
	DWORD		HP;
	DWORD		AMMO;
}PKT_PLAYER_LIFE;

typedef struct PKT_CREATE_OBJECT
{
	char		PktId;
	char		PktSize;
	OBJECT_TYPE	Object_Type;
	XMFLOAT4X4	WorldMatrix;
	int			Object_Index;
}PKT_CREATE_OBJECT;

typedef struct PKT_DELETE_OBJECT
{
	char		PktId;
	char		PktSize;
	int			Object_Index;
}PKT_DELETE_OBJECT;

struct PKT_TIME_INFO
{
	char		PktId;
	char		PktSize;
	float		elapsedtime;
};

struct PKT_UPDATE_OBJECT
{
	char		PktId;
	char		PktSize;
	int			Object_Index;
	XMFLOAT3	Object_Position;
};

struct PKT_CREATE_EFFECT
{
	char					PktId;
	char					PktSize;
	XMFLOAT3				xmf3Position;
	EFFECT_TYPE				efType;
	EFFECT_ANIMATION_TYPE	EftAnitType;
};

struct PKT_GAME_STATE
{
	char		PktId;
	char		PktSize;
	GAME_STATE	game_state;
	char		num_player;
};

typedef struct PKT_PLAYER_IN
{
	char		PktId;
	char		PktSize;
	int			id;
}PKT_PLAYER_IN, PKT_PLAYER_OUT, PKT_CLIENTID;

struct PKT_ROBBY_PLAYER_INFO
{
	char		PktId;
	char		PktSize;
	int			id;
	char		selected_robot;
};

struct PKT_GAME_START
{
	char PktID;
	char PktSize;
};

struct PKT_LOAD_COMPLETE
{
	char PktID;
	char PktSize;
};

typedef SCENE_NAME SCENEINFO;
typedef unsigned int CLIENTID;

#define MAX_NUM_OBJECT 2000
